import { Inter } from "next/font/google";
import Link from 'next/link'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OC Universe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className='grid grid-cols-10 grid-rows-10 min-h-screen'>

          <div className='md:col-span-8 2xl:col-span-9 md:row-span-1 col-span-full flex justify-center items-center'>
            <h1>{metadata.title}</h1>
          </div>

          <div className='md:col-span-2 2xl:col-span-1 md:row-span-full col-span-full flex md:flex-col justify-center md:justify-start items-center bg-stone-900'>
            <h3 className='p-4'>Navigation</h3>
            <Link className='md:w-full p-4 text-center hover:bg-green-800' href="/">home</Link>
            <Link className='md:w-full p-4 text-center hover:bg-green-800' href="/roster">roster</Link>
          </div>

          <div className='md:col-span-8 2xl:col-span-9 md:row-span-9 col-span-full row-span-8'>
            {children}
          </div>

        </div>
      </body>
    </html>
  )
}
